### ISSUE TITLE
The save photo fuctions drop a error of the sql "RETURNING" 

### ISSUE THREAD

**Issue by Glunkussss** [TORCHIZM/vlast-phone#4]
I solve all the phone thats the only error that i cant solve, if u know how to solve it i will be very happy and send u all the files
![ERROR](https://user-images.githubusercontent.com/102635797/182993605-76e932d7-7cfd-4e08-ab49-3b4a31d2a7a4.png)
![code](https://user-images.githubusercontent.com/102635797/182993616-5817ebdb-28c4-443e-aa60-dab60f8b2ce6.png)

**Comment by torchizm** [comment]
Which mariadb/mysql version you are using?

**Comment by torchizm** [comment]
It says returning keyword added in 10.5.0 version of MariaDB [here](https://mariadb.com/kb/en/insertreturning/) checkout your MariaDB version
```
"INSERT ... RETURNING was added in [MariaDB 10.5.0](https://mariadb.com/kb/en/mariadb-1050-release-notes/), and returns a resultset of the [inserted](https://mariadb.com/kb/en/insert/) rows."
```

**Comment by Glunkussss** [comment]
i will see if it works im going to open a fork :)

**Comment by torchizm** [comment]
It would be perfect if you open a pr thanks i hope it will work when you update the mariadb! :)
